# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-06 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
